language: python
python:
    - '2.7'
sudo: false
cache:
    directories:
        - "~/.platformio"
install:
    - pip install -U platformio
script:
    - pushd examples/basic && pio run && popd
    - pushd examples/dump && pio run && popd
    - pushd examples/info && pio run && popd
    - pushd examples/ota && pio run && popd
